version: '3.8'

volumes:
  postgres_data:

services:
  db:
    image: postgres:13.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
  web:
    image: valkhmyrov/yamdb_final
    restart: always
    depends_on:
      - db
    volumes:
      - ./media:/code/media
      - ./static:/code/static
    env_file:
      - ./.env
  nginx:
    image: nginx:1.19.6-alpine
    ports:
      - "80:80"
    depends_on:
      - web
    volumes:
        - ./configs/nginx.conf:/etc/nginx/conf.d/default.conf
        - ./static:/var/www/static:ro
        - ./media:/var/www/media:ro