# Generated by Django 3.0.5 on 2020-10-31 18:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Введите название категории', max_length=100, unique=True, verbose_name='Название категории')),
                ('slug', models.SlugField(help_text='Введите краткое название категории (англ.)', unique=True, verbose_name='Краткое название категории (англ.)')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Поле для коментария', verbose_name='Текст')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
            ],
            options={
                'ordering': ['-pub_date'],
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Введите название жанра', max_length=100, unique=True, verbose_name='Название жанра')),
                ('slug', models.SlugField(help_text='Введите краткое название жанра (англ.)', unique=True, verbose_name='Краткое название жанра (англ.)')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Поле для отзыва', verbose_name='Отзыв на произведение')),
                ('score', models.PositiveSmallIntegerField(help_text='Поставь оценку', validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)], verbose_name='Оценка')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
            ],
            options={
                'ordering': ['-pub_date'],
            },
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Введите название произведения', max_length=150, unique=True, verbose_name='Название произведения')),
                ('year', models.PositiveSmallIntegerField(blank=True, db_index=True, default=None, help_text='Введите год выпуска произведения', null=True, validators=[django.core.validators.MaxValueValidator(2020)], verbose_name='Год выпуска')),
                ('description', models.TextField(blank=True, help_text='Введите описание произведения', max_length=200, null=True, verbose_name='Описание произведения')),
                ('category', models.ForeignKey(blank=True, help_text='Выберите категорию произведения', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='titles', to='api.Category')),
                ('genre', models.ManyToManyField(db_index=True, help_text='Выберите жанр произведения', related_name='titles', to='api.Genre')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
