# Generated by Django 3.0.5 on 2021-02-11 21:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201031_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='description',
            field=models.TextField(blank=True, help_text='Введите описание произведения', max_length=400, null=True, verbose_name='Описание произведения'),
        ),
        migrations.AlterField(
            model_name='title',
            name='name',
            field=models.CharField(db_index=True, help_text='Введите название произведения', max_length=350, unique=True, verbose_name='Название произведения'),
        ),
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True, db_index=True, default=None, help_text='Введите год выпуска произведения', null=True, validators=[django.core.validators.MaxValueValidator(2021)], verbose_name='Год выпуска'),
        ),
    ]
