name: yamdb_final

on: [push, workflow_dispatch]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          pip install -r requirements.txt
      - name: Lint with flake8
        run: flake8 --exclude tests,api/migrations,users/migrations --max-line-length 119 .
      #- name: Test with pytest
      #  run: pytest tests.py 

  build_and_push_to_docker_hub:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    needs: tests
    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-buildx-action@v1
    - name: Login to Docker
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Push to Docker Hub
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ github.repository }}:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push_to_docker_hub
    steps:
    - uses: actions/checkout@master
    - name: Copy configuration and compose files
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.SSH_KEY }}
        passphrase: ${{ secrets.PASSPHRASE }}
        source: "configs/nginx.conf,docker-compose.yaml"
        target: ${{ github.repository }}
    - name: install\run docker-compose
      env:
        DB_NAME: ${{ secrets.DB_NAME }}
        POSTGRES_USER: ${{ secrets.POSTGRES_USER }} 
        POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.SSH_KEY }}
        passphrase: ${{ secrets.PASSPHRASE }}
        script: |
          cd ${{ github.repository }}
          if ! which docker; then touch .new_server; fi
          echo "--- Installation of Docker and Docker-Compose ---"
          if [ -f .new_server ]; then
            sudo apt-get install -y apt-transport-https ca-certificates curl gnupg-agent software-properties-common
            curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
            sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
            sudo apt-get install -y docker-ce docker-ce-cli containerd.io
            sudo curl -L "https://github.com/docker/compose/releases/download/1.28.2/docker-compose-$(uname -s)-$(uname -m)" \
              -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose
          fi

          if [ -f .new_server ]; then
            echo "--- Creation of file with secrets. Start docker-compose ---"
            echo "DB_NAME = ${{ secrets.DB_NAME }}" > .env
            echo "POSTGRES_USER = ${{ secrets.POSTGRES_USER }}" >> .env
            echo "POSTGRES_PASSWORD = ${{ secrets.PASSPHRASE }}" >> .env
            echo "DB_HOST = db" >> .env
            echo "DB_PORT = 5432" >> .env
            sudo docker-compose up -d
          else
            echo "--- Update images and start docker-compose ---"
            sudo docker-compose down
            sudo docker-compose pull
            sudo docker-compose up -d
          fi

          if [ -f .new_server ]; then
            echo "--- Make migration, collect static and add superuser ---"
            sudo docker-compose exec -T web sh -c "while ! /bin/nc -z db 5432; do echo 'DB not ready yet!'; sleep 1; done"
            sudo docker-compose exec -T web sh -c "python manage.py migrate"
            sudo docker-compose exec -T web sh -c "python manage.py collectstatic"
            sudo docker-compose exec -T web sh -c "echo 'from users.models import User; User.objects.create_superuser(\"${{ secrets.DJANGO_ADMIN }}", \"${{ secrets.DJANGO_EMAIL }}\", \" ${{ secrets.DJANGO_PASS }} \")' | python manage.py shell"
            rm -f .new_server
          fi
  
  send_message:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
    - name: send message
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: ${{ github.workflow }} успешно выполнен! 